### ISSUE TITLE
We really shouldn't expect $PWD is the directory jbrout.py is stored in

### ISSUE THREAD

**Issue by mcepl** [manatlan/jbrout3#4]
After running ``python3 setup.py develop --user`` and then running ``jbrout`` from my standard ``$PATH`` I get:
```
matej@stitny: ~$ jbrout
Will accept : ["......archiv.knihovna.repos.jbrout3.index: ['_render', 'addFolder', 'cfgGet', 'cfgSet', 'getFolders', 'getTags', 'getYear', 'getYears', 'photoBasket', 'photoRebuildThumbnail', 'photoRotateLeft', 'photoRotateRight', 'refreshFolder', 'removeBasket', 'removeFolder', 'request', 'selectFromBasket', 'selectFromFolder', 'selectFromTags', 'tagsAddCat', 'tagsAddTag', 'tagsDelCat', 'tagsDelTag', 'set', 'get']"]
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[19660:19660:1217/073816.504978:ERROR:vaapi_wrapper.cc(324)] vaInitialize failed: unknown libva error
[19660:19660:1217/073816.535212:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[19629:19629:1217/073816.787973:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const string16&, const gfx::Range&)
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/matej/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/matej/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/matej/.local/lib/python3.6/site-packages/wuy.py", line 336, in handleWeb
    html=currents[name]._render( path(os.path.dirname(ressource)) )
  File "/home/matej/archiv/knihovna/repos/jbrout3/jbrout.py", line 109, in _render
    with open( os.path.join(path,"web","index.html") ) as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matej/.local/bin/web/index.html'
INFO:aiohttp.access:::1 [17/Dec/2018:06:38:16 +0000] "GET /......archiv.knihovna.repos.jbrout3.index.html?838e8aa89e13416696144f2329d9ee91 HTTP/1.1" 500 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"
[19629:19652:1217/073817.271974:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
[19660:19660:1217/073820.861106:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!

^C<jbrout.index object at 0x7f3bbc5288d0>
matej@stitny: ~$
```
I guess jbrout still expects to be run from the code directory. It shouldn't. If you need to find the directory where the actual code is located you need to use ``os.path.dirname(__file__)``.

For fixing, there is too much magic for my taste in ``wuy``. Where does ``path`` on line 107 come from?

**Comment by manatlan** [comment]
Sure, it's too early to try to build it.
It's a wuy trouble.
Need to be fixed

Le lun. 17 déc. 2018 à 07:42, Matěj Cepl <notifications@github.com> a
écrit :

**Comment by mcepl** [comment]
I am just trying to make it comfortable to use it, so it is a less trouble to test it. Besides, I have not enough time to do anything more time demanding :(.

**Comment by manatlan** [comment]
So could you tell me how to reproduce it ?!
Did you try to do "python setup.py install", and you tried to run the
installed py script ?
Like I said wuy is not able to do that currently ... But will, one day ;-)

Le mar. 18 déc. 2018 à 17:02, Matěj Cepl <notifications@github.com> a
écrit :

**Comment by mcepl** [comment]
Even worse:
```
python3 setup.py develop --user
```
which leaves me in my ``~/.local/bin`` script ``jbrout`` like this:
```sh
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'jbrout3','console_scripts','jbrout'
__requires__ = 'jbrout3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('jbrout3', 'console_scripts', 'jbrout')()
    )
```

**Comment by manatlan** [comment]
Thanks, will try to reproduce it

Le mar. 18 déc. 2018 à 17:55, Matěj Cepl <notifications@github.com> a
écrit :

**Comment by manatlan** [comment]
should be ok ... with latest version **AND with wuy 0.9.12**

**Comment by mcepl** [comment]
Still not OK:
```
matej@stitny: ~$ jbrout
Will accept : ["......archiv.knihovna.repos.jbrout3.index: ['_render', 'addFolder', 'albumExpand', 'catExpand', 'catMoveToCat', 'catRename', 'cfgGet', 'cfgSet', 'getFolders', 'getTags', 'getYear', 'getYearMonth', 'getYears', 'photoAddTags', 'photoBasket', 'photoClearTags', 'photoComment', 'photoDelTag', 'photoRebuildThumbnail', 'photoRotateLeft', 'photoRotateRight', 'refreshFolder', 'removeBasket', 'removeFolder', 'request', 'selectFromBasket', 'selectFromFolder', 'selectFromTags', 'tagMoveToCat', 'tagsAddCat', 'tagsAddTag', 'tagsDelCat', 'tagsDelTag', 'set', 'get']"]
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[11884:11884:0104/172043.915428:ERROR:vaapi_wrapper.cc(324)] vaInitialize failed: unknown libva error
[11884:11884:0104/172043.946177:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[11853:11853:0104/172044.181491:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const string16&, const gfx::Range&)
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1 HTTP/1.1" 200 39201 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
- serve wuy.js to ......archiv.knihovna.repos.jbrout3.index (with resize to (1024, 780))
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /wuy.js HTTP/1.1" 200 6800 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/libs/web/vue.min.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /libs/vue.min.js HTTP/1.1" 404 172 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/libs/web/vuex.min.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /libs/vuex.min.js HTTP/1.1" 404 172 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/web/jbrout.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /jbrout.js HTTP/1.1" 404 172 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
Socket connected ......archiv.knihovna.repos.jbrout3.index
! 404 on /home/matej/.local/bin/web/jbrout.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /jbrout.js HTTP/1.1" 404 172 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
[11853:11865:0104/172044.298595:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
! 404 on /home/matej/.local/bin/web/favicon.ico
INFO:aiohttp.access:::1 [04/Jan/2019:16:20:44 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://localhost:8080/......archiv.knihovna.repos.jbrout3.index.html?700ca70fe33043c3a47b47c99cb1a8d1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
[11884:11884:0104/172048.258945:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[11884:11884:0104/172128.651115:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[11884:11884:0104/172128.665804:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
```
Particularly jbrout trying to open files with impossible paths like ``/home/matej/.local/bin/web/jbrout.js`` means some script doesn't find correctly, where to get resources from (``/home/matej/.local/bin/`` is obviously directory where the starting script is stored, the correct location is ``/home/matej/archiv/knihovna/repos/jbrout3/web/jbrout.js`` because ``/home/matej/.local/lib/python3.6/site-packages/easy-install.pth`` contains line ``/home/matej/archiv/knihovna/repos/jbrout3``, but it should really work automagically, just that ``jbrout.py`` (or something) should better discover its location).

**Comment by manatlan** [comment]
You have not updated your wuy ;+)
Retry and tell me

Le ven. 4 janv. 2019 à 17:26, Matěj Cepl <notifications@github.com> a
écrit :

**Comment by mcepl** [comment]
```
matej@stitny: ~$ python3 -mpip install -U wuy --user
Collecting wuy
  Downloading https://files.pythonhosted.org/packages/2f/60/754c3a70177c553f956ade84b34ea7a137127f2f4443b7e0e10a1703907d/wuy-0.9.12-py3-none-any.whl
Requirement already satisfied, skipping upgrade: aiohttp in ./.local/lib/python3.6/site-packages (from wuy) (3.4.4)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in ./.local/lib/python3.6/site-packages (from aiohttp->wuy) (1.2.6)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/lib/python3.6/site-packages (from aiohttp->wuy) (18.2.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in ./.local/lib/python3.6/site-packages (from aiohttp->wuy) (4.5.2)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in ./.local/lib/python3.6/site-packages (from aiohttp->wuy) (1.1.0)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3.6/site-packages (from aiohttp->wuy) (3.0.4)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in ./.local/lib/python3.6/site-packages (from aiohttp->wuy) (3.0.1)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp->wuy) (2.7)
Installing collected packages: wuy
  Found existing installation: wuy 0.9.5
    Uninstalling wuy-0.9.5:
      Successfully uninstalled wuy-0.9.5
Successfully installed wuy-0.9.12
matej@stitny: ~$ jbrout
Will accept : ["index: ['_render', 'addFolder', 'albumExpand', 'catExpand', 'catMoveToCat', 'catRename', 'cfgGet', 'cfgSet', 'getFolders', 'getTags', 'getYear', 'getYearMonth', 'getYears', 'photoAddTa...
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[14841:14841:0104/175546.238393:ERROR:vaapi_wrapper.cc(324)] vaInitialize failed: unknown libva error
[14841:14841:0104/175546.264342:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[14809:14809:0104/175546.478339:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const string16&, const gfx::Range&)
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /index.html?85fcbc16bdd04ab2a428ddc1785dae49 HTTP/1.1" 200 39201 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
- serve wuy.js to index (with resize to (1024, 780))
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /wuy.js HTTP/1.1" 200 7053 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/web/libs/vue.min.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /libs/vue.min.js HTTP/1.1" 404 172 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/web/libs/vuex.min.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /libs/vuex.min.js HTTP/1.1" 404 172 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/web/jbrout.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /jbrout.js HTTP/1.1" 404 172 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
Socket connected index
[14809:14830:0104/175546.596346:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
! 404 on /home/matej/.local/bin/web/jbrout.js
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /jbrout.js HTTP/1.1" 404 172 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
! 404 on /home/matej/.local/bin/web/favicon.ico
INFO:aiohttp.access:::1 [04/Jan/2019:16:55:46 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://localhost:8080/index.html?85fcbc16bdd04ab2a428ddc1785dae49" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
[14841:14841:0104/175550.552618:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[14841:14841:0104/175601.471277:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[14841:14841:0104/175601.482609:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
```

**Comment by mcepl** [comment]
Still looking for ``/home/matej/.local/bin/web/jbrout.js``.

**Comment by manatlan** [comment]
yes, you've right ...
(it worked when I commited ... it doesn't work now ?!)
I've spotted the issue, will correct tomorrow ...

i reopen it ;-)

BTW : it's really complex ... because, currently, wuy has been done, to be able to be freezed (with pyinstaller), and it's work well (at least on win) ; it finds files in the freezed exe. But it will be complex to let it works with "setup.py develop" (console script), but I like challenge ;-)

**Comment by manatlan** [comment]
now, it should REALLY work ;-)

BTW : it's possible that it can't be freezed now ... but it's in dev stage .... not really a trouble
